branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - [
      "@semantic-release/github",
      {
        "assets": [
          { "path": "build/rakuyomi-aarch64.zip", "label": "AArch64 build" },
          { "path": "build/rakuyomi-desktop.zip", "label": "Desktop (Linux) build" },
          { "path": "build/rakuyomi-kindle.zip", "label": "Kindle build" },
          { "path": "build/rakuyomi-kindlehf.zip", "label": "Kindle (hard floats) build" },
          { "path": "build/rakuyomi-kindle-legacy.zip", "label": "Kindle (legacy) build" },
          { "path": "build/settings.schema.json", "label": "Settings JSON schema" },
        ],
        "successComment": false,
      }
    ]
  - "semantic-release-export-data"
